config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  devise_for :users, controllers:
    { omniauth_callbacks: "omniauth_callbacks" }
  root 'recipes#home'

  resources :recipes do 
    resources :reviews, :only => [:create, :new]
  end
  get 'home/', to: 'recipes#home', as: :home
  get 'fridge/', to: 'users#show_fridge', as: :show_fridge
  get 'fridge/edit', to: 'users#edit_fridge', as: :edit_fridge

  get 'cookable/recipes/', to: 'recipes#can_cook', as: :can_cook
	put 'recipes/:id/cook', to: 'recipes#cook_recipe', as: :cook_recipe

  put 'fridge/update', to: 'users#update', as: :update_fridge
  get 'fridge/delete_grocery', to: 'users#del_groc', as: :del_groc

  get 'recipes/:id/delete_ingredient', to: 'recipes#del_ing', as: :del_ing
  get 'recipes/:id/add_ingredient', to: 'recipes#add_ing', as: :add_ing

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_attached_file :image, :styles=> {:medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/empty-plate.jpg"
  validates_attachment :image, :content_type => {:content_type => ["image/jpeg", "image/png", "image/gif"]}
  has_many :ingredients
  has_many :reviews
  validates_presence_of :name, :directions, :cooking_time
  validates :cooking_time, :numericality => {:greater_than => 0}
  validate :need_at_least_one_ingredient
  validate :unique_ingredients

  def fix_stars
    @my_stars = ""
    i = self.average_rating.round 
    1.upto(i) {@my_stars<<"★"} #☆⍟🌟✪✰★
    @my_stars #needed?
  end
  
  def fix_miss(miss)
    str = ""
    miss.each do |ing, miss_num|
      
      if miss_num == 1
        str << miss_num.to_s << " " << ing << ", "
      else
        str << miss_num.to_s << " " << ing.pluralize << ", "
      end
    end
    str.slice(0, str.length-2)
  end
  
  def fix_time
    @time = ""
    @mins = self.cooking_time%60
    if self.cooking_time > 60
      @hr = (self.cooking_time/60)
      @time << @hr.to_s
      if @hr == 1
        @time << " hour and "
      else
        @time << " hours and "
      end
    end
    if @mins == 1
      @time << @mins.to_s << " minute"
    else
      @time << @mins.to_s << " minutes"
    end
  end

  def update_newingredients(newingreds)
    quantities = newingreds.delete(:new_ingreds)
    names = newingreds.delete(:new_dropdown)
    units = newingreds.delete(:new_units)
    count = 0
    if(quantities != nil)
      quantities.each do |ing|
        if(ing[1].to_i > 0)
          count = count + 1
          self.ingredients.new(:quantity => ing[1].to_i, :food_id => "#{Food.find_by('name = ?', names[ing[0].to_sym].to_s).id}", :unit_id => "#{Unit.find_by('unit = ?', units[ing[0].to_sym].to_s).id}")
        end
      end
    end
    count
  end

  def update_ingredients(old)
    quantities = old.delete(:ingreds)
    names = old.delete(:dropdown)
    units = old.delete(:units)
    error = check_updates(names)
    if !error
      if(quantities != nil)
        quantities.each do |ing|
          ing[0] =~ /^ingredient_(\d+)/
          if (ing[1].to_i > 0)
            Ingredient.find($1).update(:quantity => "#{ing[1]}", :food_id => "#{Food.find_by('name = ?', names[ing[0].to_sym].to_s).id}", :unit_id => "#{Unit.find_by('unit = ?', units[ing[0].to_sym].to_s).id}")
          else#quant is a bad number
            Ingredient.find($1).destroy #HIT THIS
          end
        end
      end
    end
    error
  end

  def check_updates(names)
    name_arr = names.values
    err = false
    if (name_arr != name_arr.uniq)
      err = true
      errors[:unique_ingredients] << "are needed"
    end
    err
  end

  def self.search(search)
    Recipe.where("name like ?", "%#{search}%")
  end

  def self.sorted_by(col)
    if self.column_names.include?(col)
      if col == "average_rating"
        s = self.order("#{col} DESC")
      else
        s = self.order(col)
      end
    else
      self.order("name")
    end
  end

  def self.filter(time)
    if (time == nil || time == "")
      self.all
    else
      self.where("cooking_time <= ?", time)
    end
  end

  def update_avg_rating(new_rating)
    if (new_rating != nil)
      count = self.reviews.length + 1
      rating = new_rating
      self.reviews.each do |r|
        rating += r.stars
      end
      self.average_rating = rating.to_f / count.to_f
    end
  end

  def cook_helper(user)
    missing_ingred = Hash.new()
    my_groceries = grocery_list(user) # { Food Name : Grocery Quantity }
    Ingredient.where('recipe_id = ?', self.id).each do |ingred|
        if (my_groceries[ingred.food.name] == nil)
            missing_ingred[ingred.food.name] = ingred.quantity
        elsif (my_groceries[ingred.food.name] < ingred.quantity)
            f = Food.find_by("name = ?","#{ingred.food.name}")
            g = Grocery.where('user_id = ?', user.id).find_by("food_id = ?", f.id)
            User.delete_grocery(g)
        elsif (my_groceries[ingred.food.name] == ingred.quantity)
            
            f = Food.find_by("name = ?", "#{ingred.food.name}")
            g = Grocery.where("user_id = ?", user.id).find_by("food_id = ?", f.id)
            User.delete_grocery(g)
        else
            f = Food.find_by("name = ?", "#{ingred.food.name}")
	    g = Grocery.where('user_id = ?', user.id).find_by("food_id = ?", f.id)
	    g.update(:quantity => "#{(g.quantity - ingred.quantity)}")
        end
    end
  end

  def self.sort_cook(cookable)
    zero = []
    one = []
    two = []
    cookable.each do |k, v|
      if(v.length == 0)
        zero << {k => v}
      end
      if(v.length == 1)
        one << {k => v}
      end
      if(v.length == 2)
        two << {k => v}
      end
    end
    zero.concat(one).concat(two)
  end

def lacking(user)
## this method takes a recipe and a user and creates a hash with the food lacking in a fridge to make a recipe
    lacking = Hash.new()
    my_groceries = grocery_list(user) # returns hash of {Food name : Grocery quantity}
    self.ingredients.each do |ingred|
        if (my_groceries[ingred.food.name] == nil)
            lacking[ingred.food.name] = ingred.quantity
        elsif (my_groceries[ingred.food.name] < ingred.quantity)
            lacking[ingred.food.name] = (ingred.quantity - my_groceries[ingred.food.name])
        end
    end
    lacking
end

def grocery_list(user)
## given a user, this method creates a hash list of groceries in a user's fridge
## { Food Name : Grocery Quantity }
    my_groceries = Hash.new()
    user.groceries.each do |grocery|
        my_groceries[grocery.food.name] = grocery.quantity
    end
    return my_groceries
end

  private

  def need_at_least_one_ingredient
    if self.ingredients.length == 0
      errors[:need_at_least_one_ingredient] << "when saving recipe"
    end
  end

  def unique_ingredients
    ing_arr = self.ingredients.map do |x|
      x.food.name
    end
    if (ing_arr != ing_arr.uniq)
      errors[:unique_ingredients] << "are needed"
    end
  end
      

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
 
  def index
    if params[:query] != nil
      session[:query] = params[:query]
    end
    if params[:cooking_time] != nil
      session[:cooking_time] = params[:cooking_time]
    end
    if params[:recipe_name] != nil
      session[:recipe_name] = params[:recipe_name]
    end
    redirect = handle_redirects
    if !redirect
      if params[:query] == nil
        @recipes = Recipe.filter(params[:cooking_time]).search(params[:recipe_name]).sorted_by("name")
      else
        @recipes = Recipe.filter(params[:cooking_time]).search(params[:recipe_name]).sorted_by(params[:query])
      end
      if @recipes.length == 0
        reset_search
      end
    end
  end

def can_cook()
    limit = 2
    cookable = Hash.new
    Recipe.all.each do |r|
        missing_ingred = r.lacking(@user)
        if missing_ingred.length <= limit
            cookable[r] = missing_ingred
        end
    end
    coo = Recipe.sort_cook(cookable)
    @my_cookable = coo
    render :index and return
end

def cook_recipe()
    recipe = Recipe.find(params.delete(:id))
    recipe.cook_helper(@user)
    flash[:notice] = "Hope you enjoyed, #{recipe.name}"
    redirect_to show_fridge_path
end


def new
  @recipe = Recipe.new #possibly replace this with a helper 
end


def del_ing
  Ingredient.find(params[:ing_id]).destroy
  redirect_to edit_recipe_path(Recipe.find(params[:id]), :additional => params[:additional])
end


def create
  add = params.delete(:additional)
  ingreds = params.delete(:newingreds)
  params[:recipe][:average_rating] = 0
  r=Recipe.new(create_params)
  r.update_newingredients(ingreds)
  if r.save
    flash[:notice] = "New recipe #{r.name} was made"
    if add
        redirect_to edit_recipe_path(r, :additional => "1")
      else
        redirect_to recipes_path
      end
  else
    flash[:notice] = "The create didn't work :(  "
    flash[:notice] << r.errors.full_messages.join(". ") << "."
    redirect_to new_recipe_path(:additional => 1)
  end
end

def show
  @recipe = Recipe.find(params[:id])
end

#added simple edit metod to fix the null item error
def edit
  @recipe = Recipe.find(params[:id])
end

def update
  add = params.delete(:additional)
  oldingreds = params.delete(:old)
  newingreds = params.delete(:new)
  @recipe = Recipe.find(params[:id])
  if oldingreds
    error = @recipe.update_ingredients(oldingreds)
    if error
      flash[:notice] = "The update failed :(   "
      flash[:notice] << @recipe.errors.full_messages.join(". ") << "."
      redirect_to edit_recipe_path(@recipe) and return
    end
  end
  ingreds_added=0
  if (newingreds != nil)
    ingreds_added = @recipe.update_newingredients(newingreds)
  end
  @recipe.update(update_params)
  if @recipe.save#wont fail until we add validations or force in rspec tests
    flash[:notice] = "You updated #{@recipe.name}"
    if add 
      add = add.keys[0].to_i
      draw = add - ingreds_added
      redirect_to edit_recipe_path(@recipe, :additional => "#{draw}")
    else
      redirect_to recipe_path(@recipe) #redirect to the show
    end
  else
    flash[:notice] = "The update failed :(   "
    flash[:notice] << @recipe.errors.full_messages.join(". ") << "."
    if @recipe.errors.has_key?(:need_at_least_one_ingredient)
      redirect_to edit_recipe_path(@recipe, {:additional => 1}) #redirect back to the edit page
    else
      redirect_to edit_recipe_path(@recipe)
    end
  end
end

private

#added but still need to add the validations in the class
def update_params
  #mess with ingredients eventually
  params.require(:recipe).permit(:name, :directions, :cooking_time, :image)
end

def create_params
  params.require(:recipe).permit(:name, :directions, :cooking_time, :image, :average_rating)
end

def handle_redirects
  hash = Hash.new
  redirect = false
  if !params.has_key?(:cooking_time) && session.has_key?(:cooking_time) && session[:cooking_time] != ""
    hash[:cooking_time] = session[:cooking_time]
    hash[:query] = params[:query] unless !params.has_key?(:query)
    hash[:recipe_name] = params[:recipe_name] unless !params.has_key?(:recipe_name)
    redirect = true
  end
  #should have cooking time set
  if !params.has_key?(:query) && session.has_key?(:query) && session[:query] != ""
    hash[:query] = session[:query]
    hash[:cooking_time] = params[:cooking_time] unless !params.has_key?(:cooking_time)
    hash[:recipe_name] = params[:recipe_name] unless !params.has_key?(:recipe_name)
    redirect = true
  end
  if !params.has_key?(:recipe_name) && session.has_key?(:recipe_name) && session[:recipe_name] != ""
    hash[:recipe_name] = session[:recipe_name]
    hash[:cooking_time] = params[:cooking_time] unless !params.has_key?(:cooking_time)
    hash[:query] = params[:query] unless !params.has_key?(:query)
    redirect = true
  end
  if redirect
    flash.keep
    redirect_to recipes_path(hash)
    true
  else

    false
  end
end

def reset_search
  flash[:notice] = "No recipes found"
  hash = Hash.new
  hash[:recipe_name] = ""
  hash[:cooking_time] = ""
  redirect_to recipes_path(hash) and return
end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_cookview.html.haml
%table.table.table-hover.recipes_table
  %tr.recipes_header
    %th Name
    %th Image
    %th Cooking Time
    %th Ratings
    %th Missing Ingredients
  -@my_cookable.each do |c|
    -c.each do |r, missing_i|
      %tr.recipe_row
        %td.recipe_name= link_to r.name, recipe_path(r.id)
        %td= image_tag(r.image.url(:thumb))
        %td#time= r.fix_time
        - if r.average_rating != 0
          %td.rating#starry= r.fix_stars
        -else
          %td.rating Not yet rated!
        -if missing_i.length == 0
          %td.cook= link_to "Cook Recipe", {:controller => "recipes", :id => "#{r.id}", :action => "cook_recipe"}, method: :put
        -else
          %td.cook= r.fix_miss(missing_i)
= link_to "Create a new recipe", new_recipe_path(:additional => 1)

app/views/recipes/_login.html.haml
- if (@user)
  %p.login
    = @user.get_name 
    |
    =link_to " Sign Out", destroy_user_session_path, :method => "delete"
    |
    =link_to "My fridge", show_fridge_path
- else
  %p.login
    Welcome
    |
    = link_to "Login", (new_user_session_path)

app/views/recipes/_login2.html.haml
- if (@user)
  %p.login
    = @user.get_name 
    |
    =link_to " Sign Out", destroy_user_session_path, :method => "delete"
    |
    =link_to "My fridge", show_fridge_path
- else
  %p.login
    Welcome
    |
    = link_to "Login", (new_user_session_path)

app/views/recipes/_regview.html.haml
%table.table.table-hover.recipes_table
  %tr.recipes_header
    %th= link_to "Name", recipes_path(:query => "name")
    %th Image
    %th= link_to "Cooking Time", recipes_path(:query => "cooking_time")
    %th= link_to "Ratings", recipes_path(:query => "average_rating")
  -@recipes.each do |r|
    %tr.recipe_row
      %td.recipe_name= link_to r.name, recipe_path(r.id)
      %td= image_tag(r.image.url(:thumb))
      %td#time= r.fix_time
      - if r.average_rating != 0
        %td.rating#starry= r.fix_stars
      -else
        %td.rating Not yet rated!
= link_to "Create a new recipe", new_recipe_path(:additional => 1)

app/views/recipes/_search_and_filter.html.haml
= form_tag recipes_path, method: :get do
  = label_tag "recipe_name"
  = text_field_tag "recipe_name", nil, maxlength: 10
  = submit_tag "Search Recipes"
= form_tag('/recipes', method: :get) do
  = label_tag(:cooking_time, "Meals in:")
  = number_field_tag(:cooking_time, nil, min: 0)
  = submit_tag("Filter recipes")

app/views/recipes/edit.html.haml
=render 'login'
#main
  %h4= flash[:notice] if flash[:notice]
  %h2 Edit Recipe Details
  = form_for @recipe, :method => :put do |f|
    =f.label :name
    =f.text_field :name
    %br
    =f.label :directions
    =f.text_field :directions
    %br
    =f.label :cooking_time
    =f.number_field :cooking_time
    %br
    %table
      %tr
        %th Ingredient
        %th Quantity
        %th Units
        %th Delete Ingredient
      -@recipe.ingredients.each do |i|
        %tr
          %td
            <select name = "old[dropdown[ingredient_#{i.id}]]" id="food_select_#{i.id}">
            -Food.all.each do |foo|
              -if foo.name == i.food.name
                %option{:selected => "#{foo.name}"}=foo.name
              -else
                %option= foo.name
            </select>
          %td <input type = "number" name = "old[ingreds[ingredient_#{i.id}]]" value = "#{i.quantity}">
          %td.units
            <select name = "old[units[ingredient_#{i.id}]]" id = "unit_select_#{i.id}">
            -Unit.all.each do |foo|
              -if foo.unit == i.unit.unit
                %option{:selected => "#{foo.unit}"}=foo.unit
              -else
                %option= foo.unit
            </select>
          %td= link_to "Bye bye", {:controller => "recipes", :action => "del_ing", :id => "#{@recipe.id}", :ing_id => "#{i.id}", :additional => params[:additional]}, class: "del_ing"
      -if params.has_key?(:additional)
        -(1..params[:additional].to_i).each do |x|
          %tr
            %td
              <select name = "new[new_dropdown[newingredient_#{x}]]" id="newfood_select_#{x}">
              -Food.all.each do |foo|
                %option= foo.name
              </select>
            %td <input type = "number" name = "new[new_ingreds[newingredient_#{x}]]">
            %td.units
              <select name = "new[new_units[newingredient_#{x}]]" id = "newunit_select_#{x}">
              -Unit.all.each do |foo|
                %option= foo.unit
              </select>
            -if params[:additional] == "1"
              %td= link_to "Bye bye", edit_recipe_path(@recipe), class: "del_ing" 
            -else
              %td= link_to "Bye bye", edit_recipe_path(@recipe, :additional => (params[:additional].to_i - 1).to_s), class: "del_ing"
    -if params.has_key?(:additional)
      =submit_tag("Add ingredient", :name => "additional[#{params[:additional].to_i+1}]")
    -else
      =submit_tag("Add ingredient", :name => "additional[1]")
    %br
    =f.label :image
    =f.file_field :image
    %br
    =f.submit 'Update Recipe Details'
    %br
  =link_to "Back to #{@recipe.name} page", recipe_path(@recipe)
  =link_to "Back to recipe index list", recipes_path()

app/views/recipes/home.html.haml
=render 'login2'
#title
  AskSamantha
  %p
  = image_tag("sam.jpg")
%p
%p
%p
#search
  =render 'search_and_filter'
  %p
  = link_to "Check out the recipes!", recipes_path

app/views/recipes/index.html.haml
= render 'login'
#shift
  %h4= flash[:notice] if flash[:notice] 
  .page-header
    %h3 All Recipes
  =render 'search_and_filter'
  -if @my_cookable != nil && @my_cookable.length>0
    = render 'cookview'
  -elsif @my_cookable != nil &&  @my_cookable.length == 0
    %h1 You are more than two ingredients away from all recipes, go shopping!
  -else
    = render 'regview'
  %br
  -if @user && @my_cookable==nil
    =link_to "What can I cook?", {:controller => "recipes", :action => "can_cook"}
  -elsif @user
    =link_to "View All", {:controller => "recipes", :action => "index"}
  %br
  %br

app/views/recipes/new.html.haml
=render 'login'
#main
  %h4= flash[:notice] if flash[:notice]
  %h2 Create a New Recipe
  = form_for @recipe do |f|

    =f.label :name
    =f.text_field :name
    %br
    =f.label :directions
    =f.text_field :directions
    %br
    =f.label :cooking_time
    =f.number_field :cooking_time
    %br
    %table
      %tr
        %th Ingredient
        %th Quantity
        %th Units
        %th Delete Ingredient
      -if params.has_key?(:additional)
        -(1..params[:additional].to_i).each do |x|
          %tr
            %td
              <select name = "newingreds[new_dropdown[newingredient_#{x}]]" id="newfood_select_#{x}">
              -Food.all.each do |foo|
                %option= foo.name
              </select>
            %td#test <input type = "number" name = "newingreds[new_ingreds[newingredient_#{x}]]">
            %td.units
              <select name = "newingreds[new_units[newingredient_#{x}]]" id = "newunit_select_#{x}">
              -Unit.all.each do |foo|
                %option= foo.unit
              </select>
            -if params[:additional] == "1"
              %td= link_to "Bye bye", new_recipe_path(@recipe)
            -else
              %td= link_to "Bye bye", new_recipe_path(@recipe, :additional => (params[:additional].to_i - 1).to_s)
    -if params.has_key?(:additional)
      =submit_tag("Add ingredient", :name => "additional[#{params[:additional].to_i+1}]")
    -else
      =submit_tag("Add ingredient", :name => "additional[1]")
    %br
    =f.label :image
    =f.file_field :image
    %br
    =f.submit 'Create Recipe'
    %br
    %br
    =link_to "Back to Recipe Index", recipes_path()

app/views/recipes/show(option2).html.haml
#main
  %h4= flash[:notice] if flash[:notice] 
  %h3= "Recipe Details For #{@recipe.name}"
  %table.recipes_table
    %tr.recipes_header
      %th Image
      %th Cooking Time
    %tr
      %td= image_tag(@recipe.image.url(:medium))
      %td#Cooking_Time= @recipe.cooking_time
  %table.recipes_info
    %tr
      %th Directions
      %th Ingredients
    %tr.recipe_row
      %td= @recipe.directions
      %td
        %table
          %tr
            %th Name
            %th Quantity
          -@recipe.ingredients.each do |i|
            %tr.ingredient_row
              %td= i.name
              %td= i.quantity
  = link_to "Edit recipe details", edit_recipe_path
  = link_to "Back to recipes!", recipes_path

app/views/recipes/show.html.haml
=render 'login'
#main
  = link_to "Back to recipes!", recipes_path
  %h4= flash[:notice] if flash[:notice] 
  %h3= "Recipe Details For #{@recipe.name}"
  %table.recipes_table.table
    %tr.recipes_header
      %th Image
      %th Cooking Time
    %tr
      %td= image_tag(@recipe.image.url(:medium))
      %td#Cooking_Time= @recipe.fix_time
  %br
  %table.table.recipes_info
    %tr
      %th Ingredients
    %tr.recipe_row
      %td
        %table.table.table-hover
          %tr
            %th Name
            %th Quantity
          -@recipe.ingredients.each do |i|
            %tr.ingredient_row
              %td.name= i.food.name
              %td.quantity= i.format_quantity
  %table.recipes_directions
    %tr
      %th Directions
    %tr
      %td#directions=  @recipe.directions
  %table.recipes_reviews
    %tr  
      %th Reviews
    -if @recipe.reviews == []
      %tr
        %td Write the first review!
    -else
      %tr
        %td
          %table
            %tr.review_header
              %th Stars
              %th Comments
              %th User
            %tr
              -@recipe.reviews.each do |rev|
                %tr.review_row
                  %td.starry_show=rev.show_stars
                  %td.comment=rev.comments
                  %td.user= rev.user.get_name


  = link_to "Edit recipe details", edit_recipe_path
  %br
  -if @user
    = link_to "Write a Review", new_recipe_review_path(@recipe)
    %br
    =link_to "Cook Recipe", {:controller => "recipes", :id => "#{@recipe.id}", :action => "cook_recipe"}, method: :put
  -else
    = link_to "Sign in to Review!", (new_user_session_path)