config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  devise_for :users, controllers:
    { omniauth_callbacks: "omniauth_callbacks" }
  root 'recipes#home'

  resources :recipes do 
    resources :reviews, :only => [:create, :new]
  end
  get 'home/', to: 'recipes#home', as: :home
  get 'fridge/', to: 'users#show_fridge', as: :show_fridge
  get 'fridge/edit', to: 'users#edit_fridge', as: :edit_fridge

  get 'cookable/recipes/', to: 'recipes#can_cook', as: :can_cook
	put 'recipes/:id/cook', to: 'recipes#cook_recipe', as: :cook_recipe

  put 'fridge/update', to: 'users#update', as: :update_fridge
  get 'fridge/delete_grocery', to: 'users#del_groc', as: :del_groc

  get 'recipes/:id/delete_ingredient', to: 'recipes#del_ing', as: :del_ing
  get 'recipes/:id/add_ingredient', to: 'recipes#add_ing', as: :add_ing

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :reviews
  has_many :groceries
  validate :unique_groceries
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:github]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.user_name = auth.info.user_name # assuming the user model has a name
      user.password = Devise.friendly_token[0,20]
    end
  end

  def get_name
    email = self.email
    email =~ /^(.+)@/
    $1
  end

  def self.delete_grocery(g)
    Grocery.find(g.id).destroy
  end

  def update_fridge(oldgrocs)
    quantities = oldgrocs.delete(:groc)
    names = oldgrocs.delete(:dropdown)
    units = oldgrocs.delete(:units)
    error = self.check_updates(names)
    if !error
      if(quantities != nil)
        quantities.each do |g|
          g[0] =~ /^grocery_(\d+)/
          if (g[1].to_i > 0)
            Grocery.find($1).update(:quantity => "#{g[1]}", :food_id => "#{Food.find_by('name = ?', names[g[0].to_sym].to_s).id}", :unit_id => "#{Unit.find_by('unit = ?', units[g[0].to_sym].to_s).id}")
          else#quant is a bad number
            Grocery.find($1).destroy #HIT THIS
          end
        end
      end
    end
    error
  end

  def update_fridge_new(newgrocs)
    quantities = newgrocs.delete(:new_grocs)
    names = newgrocs.delete(:new_dropdown)
    units = newgrocs.delete(:new_units)
    count = 0
    if(quantities != nil)
      quantities.each do |g|
        
        if(g[1].to_i > 0)
          count = count+1
          self.groceries.new(:quantity => g[1].to_i, :food_id => "#{Food.find_by('name = ?', names[g[0].to_sym].to_s).id}", :unit_id => "#{Unit.find_by('unit = ?', units[g[0].to_sym].to_s).id}")
          
        end
      end
    end
    #byebug
    count
  end

  def check_updates(names)
    name_arr = names.values
    err = false
    if (name_arr != name_arr.uniq)
      err = true
      errors[:unique_groceries] << "are needed"
    end
    err
  end

  private

  def unique_groceries
    groc_arr = self.groceries.map do |x|
      x.food.name
    end
    if (groc_arr != groc_arr.uniq)
      errors[:unique_groceries] << "are needed"
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show_fridge
    @groceries = @user.groceries if @user
  end

  def edit_fridge
  end

  def del_groc
    Grocery.find(params[:groc_id]).destroy
    redirect_to edit_fridge_path(:additional => params[:additional])
  end


  def update
    add = params.delete(:additional)
    old_grocs = params.delete(:oldgrocs)
    if old_grocs
      error = @user.update_fridge(old_grocs)
      if error
        flash[:notice] = "Fridge update failed :(  "
        flash[:notice] << @user.errors.full_messages.join(". ") << "."
        redirect_to edit_fridge_path and return
      end
    end
    new_grocs = params.delete(:newgrocs)
    new_added=0
    if (new_grocs != nil)
      #byebug
      new_added= @user.update_fridge_new(new_grocs)
    end
    if @user.save  #wont fail until we add validations or force in rspec tests
      flash[:notice] = "Fridge successfully updated!"
      if add 
        add = add.keys[0].to_i
        draw= add-new_added
        redirect_to edit_fridge_path(:additional => "#{draw}")
      else
        redirect_to show_fridge_path
      end
    else
      flash[:notice] = "Fridge update failed :(  "
      flash[:notice] << @user.errors.full_messages.join(". ") << "."
      redirect_to edit_fridge_path
    end
  end
  
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_editloggedin.html.haml
= form_tag update_fridge_path, method: :put do
  %table
    %tr
      %th Name
      %th Quantity
      %th Units
      %th Delete Grocery
    -@user.groceries.each do |g|
      %tr
        %td
          <select name = "oldgrocs[dropdown[grocery_#{g.id}]]" id="food_select_#{g.id}">
          -Food.all.each do |foo|
            -if foo.name == g.food.name
              %option{:selected => "#{foo.name}"}=foo.name
            -else
              %option= foo.name
          </select>
        %td <input type = "number" name = "oldgrocs[groc[grocery_#{g.id}]]" value = "#{g.quantity}">
        %td.units
          <select name = "oldgrocs[units[grocery_#{g.id}]]" id = "unit_select_#{g.id}">
          -Unit.all.each do |foo|
            -if foo.unit == g.unit.unit
              %option{:selected => "#{foo.unit}"}=foo.unit
            -else
              %option= foo.unit
          </select>
        %td= link_to "Delete grocery", {:controller => "users", :action => "del_groc", :groc_id => "#{g.id}", :additional => params[:additional]}, class: "del_groc"
    -if !params.has_key?(:additional) && @user.groceries.length == 0
      -params[:additional] = "1"
    -if params.has_key?(:additional)
      -(1..params[:additional].to_i).each do |x|
        %tr
          %td
            <select name = "newgrocs[new_dropdown[newgrocery_#{x}]]" id="newfood_select_#{x}">
            -Food.all.each do |foo|
              %option= foo.name
            </select>
          %td <input type = "number" name = "newgrocs[new_grocs[newgrocery_#{x}]]">
          %td.units
            <select name = "newgrocs[new_units[newgrocery_#{x}]]" id = "newunit_select_#{x}">
            -Unit.all.each do |foo|
              %option= foo.unit
            </select>
          -if params[:additional] == "1"
            %td= link_to "Delete grocery", edit_fridge_path, class: "del_groc" 
          -else
            %td= link_to "Delete grocery", edit_fridge_path(:additional => (params[:additional].to_i - 1).to_s), class: "del_groc"
  %br
  -if params.has_key?(:additional)
    =submit_tag("Add grocery", :name => "additional[#{params[:additional].to_i+1}]")
  -else
    =submit_tag("Add grocery", :name => "additional[1]")
  %br
  =submit_tag('Update Fridge!')
  %br

app/views/users/_editnotlogged.html.haml
%h1 Login to edit your fridge!
=link_to "Back to Home Page", recipes_path

app/views/users/_login.html.haml
%h1 AskSamantha
- if (@user)
  %p.login
    = @user.get_name 
    |
    =link_to " Sign Out", destroy_user_session_path, :method => "delete"
    |
    =link_to "My fridge", show_fridge_path
- else
  %p.login
    Welcome
    |
    = link_to "Login", (new_user_session_path)

app/views/users/_loginview.html.haml
%h4= flash[:notice] if flash[:notice] 
%h3 My Fridge
-if @groceries != []
  %table.groceries_table
    %tr.groceries_header
      %th Name
      %th Quantity
    -@groceries.each do |g|
      %tr.grocery_row
        %td.name= g.food.name
        %td.quantity= g.format_quantity
-else
  %p Add some ingredients to your fridge!
=link_to "Update fridge!", edit_fridge_path
%br
=link_to "What can I cook?", {:controller => "recipes", :action => "can_cook"}

app/views/users/_notlogview.html.haml
%h1 Login to view your fridge!
=link_to "Back to Home Page", recipes_path

app/views/users/edit_fridge.html.haml
=render 'login'
#main
  %h4= flash[:notice] if flash[:notice]
  %h2 Edit Fridge
  -if @user
    =render 'editloggedin'
  -else
    =render 'editnotlogged'
  %br
  = link_to "Back to Fridge", show_fridge_path()
  %br
  = link_to "Back to recipes!", recipes_path

app/views/users/show_fridge.html.haml
= render 'login'
#main
  
  -if @user
    =render 'loginview'
  -else
    =render 'notlogview'
  %p
  = link_to "Back to recipes!", recipes_path