config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  devise_for :users, controllers:
    { omniauth_callbacks: "omniauth_callbacks" }
  root 'recipes#home'

  resources :recipes do 
    resources :reviews, :only => [:create, :new]
  end
  get 'home/', to: 'recipes#home', as: :home
  get 'fridge/', to: 'users#show_fridge', as: :show_fridge
  get 'fridge/edit', to: 'users#edit_fridge', as: :edit_fridge

  get 'cookable/recipes/', to: 'recipes#can_cook', as: :can_cook
	put 'recipes/:id/cook', to: 'recipes#cook_recipe', as: :cook_recipe

  put 'fridge/update', to: 'users#update', as: :update_fridge
  get 'fridge/delete_grocery', to: 'users#del_groc', as: :del_groc

  get 'recipes/:id/delete_ingredient', to: 'recipes#del_ing', as: :del_ing
  get 'recipes/:id/add_ingredient', to: 'recipes#add_ing', as: :add_ing

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_filter :authenticate_user!
   def create
      @recipe = Recipe.find(params[:recipe_id])
      params[:review][:user_id] = @user.id
      @review = Review.new(create_update_params)
      @recipe.update_avg_rating(@review.stars)
      @recipe.reviews << @review
      if @recipe.save
         flash[:notice] = 'Review successfully created!'
         redirect_to(recipe_path(@recipe))
      else
         flash[:notice] = 'Failure to create new review! '
         flash[:notice] << @review.errors.full_messages.join(". ") << "."
         redirect_to(new_recipe_review_path(@recipe))
      end
   end

   def new
      @recipe = Recipe.find(params[:recipe_id])
      @review = Review.new
   end

private
   def create_update_params
      params.require(:review).permit(:stars, :comments, :user_id)
   end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_login.html.haml
%h1 AskSamantha
- if (@user)
  %p.login
    = @user.get_name 
    |
    =link_to " Sign Out", destroy_user_session_path, :method => "delete"
    |
    =link_to "My fridge", show_fridge_path
- else
  %p.login
    Welcome
    |
    = link_to "Login", (new_user_session_path)

app/views/reviews/new.html.haml
=render 'login'
#main
  %h4= flash[:notice] if flash[:notice]
  %h2 Create a New Review
	
  = form_for [@recipe, @review], :method => :post do |f|
    %table
      %tr
        %th Comments
        %th Stars
      %tr
        %td
          =f.text_field :comments
        %td
          <select name = "review[stars]" id = "review_stars">
          -(1..5).each do |x|
            %option= x
          </select>
    %br
    =f.submit 'Post Review'
    %br
    =link_to "Back to Recipe", recipes_path()